name: base_flutter
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  equatable:
  auto_route: ^2.0.2
  flutter_local_notifications: ^5.0.0+3
  shared_preferences: ^2.0.5
  flutter_launcher_icons: ^0.9.0
  url_launcher: ^6.0.3
  firebase_messaging: ^9.1.3
  firebase_core: ^1.1.0
  flutter_spinkit: ^5.0.0
  page_view_indicator: ^2.0.4
  flutter_staggered_animations: ^1.0.0
  google_maps_flutter: ^2.0.3
  location: ^4.1.1
  geolocator: ^7.0.3
  photo_view: ^0.11.1
  cached_network_image: ^3.0.0
  intl: ^0.17.0
  flutter_rating_bar: ^4.0.0
  bot_toast: ^4.0.1
  flutter_easyloading: ^3.0.0
  flutter_phoenix: ^1.0.0
  google_fonts: ^2.0.0
  flutter_swiper: ^1.1.6
  modal_bottom_sheet: ^2.0.0
  file_picker: ^3.0.1
  share: ^2.0.1
  flutter_rounded_date_picker: ^2.0.1
  material_design_icons_flutter: ^4.0.5955
  map_launcher: ^2.0.0
  json_serializable: ^4.1.1
  json_annotation: ^4.0.1
  dio_cache_interceptor: ^2.2.0
  pretty_dio_logger: ^1.1.1
  flutter_html: ^1.3.0
  pin_code_fields: ^7.0.0
  dots_indicator: ^1.2.0
  curved_navigation_bar:
  animated_bottom_navigation_bar: ^0.2.1





flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/appIcon.png"



dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: any
  build_runner: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/appIcon.png
    - assets/images/bg.png
    - assets/images/bgheader.png
    - assets/images/facebook.png
    - assets/images/logo.png
    - assets/images/noun_mapp.png
    - assets/images/noun_men.png
    - assets/images/on1.png
    - assets/images/on2.png
    - assets/images/on3.png
    - assets/images/onProv1.png
    - assets/images/onProv2.png
    - assets/images/onProv3.png
    - assets/images/onUser4.png
    - assets/images/pic.jpg
    - assets/images/twitter.png
    - assets/images/vedioImg.png
    - assets/images/wha.png
    - assets/lang/ar.json
    - assets/lang/en.json
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
