import 'dart:io';

import 'package:auto_route/auto_route.dart';
import 'package:base_flutter/company/models/dots/AddSubscribeModel.dart';
import 'package:base_flutter/company/screens/company_subscribe/CompanySubscribeImports.dart';
import 'package:base_flutter/company/screens/company_subscribe/tabs/first_step/widgets/FirstStepWidgetsImports.dart';
import 'package:base_flutter/company/screens/company_subscribe/widgets/CompanySubscribeWidgetsImports.dart';
import 'package:base_flutter/general/blocks/generic_cubit/generic_cubit.dart';
import 'package:base_flutter/general/blocks/user_cubit/user_cubit.dart';
import 'package:base_flutter/general/constants/CustomButtonAnimation.dart';
import 'package:base_flutter/general/constants/MyColors.dart';
import 'package:base_flutter/general/utilities/routers/RouterImports.gr.dart';
import 'package:base_flutter/general/utilities/utils_functions/UtilsImports.dart';
import 'package:base_flutter/general/widgets/DefaultAppBar.dart';
import 'package:base_flutter/general/widgets/DefaultButton.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
part 'FirstStep.dart';
part 'FirstStepData.dart';