import 'package:auto_route/auto_route.dart';
import 'package:base_flutter/company/screens/company_opinion_subscribe/CompOpinionSubscribeImports.dart';
import 'package:base_flutter/company/screens/company_subscribe/CompanySubscribeImports.dart';
import 'package:base_flutter/general/blocks/generic_cubit/generic_cubit.dart';
import 'package:base_flutter/general/constants/MyColors.dart';
import 'package:base_flutter/general/utilities/routers/RouterImports.gr.dart';
import 'package:base_flutter/general/widgets/CachedImage.dart';
import 'package:base_flutter/general/widgets/DefaultButton.dart';
import 'package:base_flutter/general/widgets/MyText.dart';
import 'package:base_flutter/res.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

part 'BuildButtonList.dart';
part 'BuildDetailsView.dart';
part 'BuildImages.dart';
part 'BuildVideosView.dart';
part 'BuildPriceView.dart';
part 'BuildReviewItem.dart';