/// Generated by AssetsRefGenerator on 2021/05/17
class Res {
  static const String appIcon = "assets/images/appIcon.png";
  static const String bg = "assets/images/bg.png";
  static const String bgheader = "assets/images/bgheader.png";
  static const String logo = "assets/images/logo.png";
  static const String noun_mapp = "assets/images/noun_mapp.png";
  static const String noun_men = "assets/images/noun_men.png";
  static const String on1 = "assets/images/on1.png";
  static const String on2 = "assets/images/on2.png";
  static const String on3 = "assets/images/on3.png";
  static const String onProv1 = "assets/images/onProv1.png";
  static const String onProv2 = "assets/images/onProv2.png";
  static const String onProv3 = "assets/images/onProv3.png";
  static const String onUser4 = "assets/images/onUser4.png";
  static const String vedioImg = "assets/images/vedioImg.png";
}
