import 'package:base_flutter/company/screens/company_special_subscribe/CompSpecialSubscribeImports.dart';
import 'package:base_flutter/company/screens/company_subscribe/tabs/third_step/widgets/ThirdStepWidgetsImports.dart';
import 'package:base_flutter/general/constants/MyColors.dart';
import 'package:base_flutter/general/widgets/DefaultButton.dart';
import 'package:base_flutter/general/widgets/MyText.dart';
import 'package:flutter/material.dart';
part 'BuildReviewDetails.dart';
part 'BuildReviewPrice.dart';
part 'BuildButtonList.dart';