import 'package:base_flutter/company/screens/company_brochure_subscribe/tabs/first_step_brochure/widgets/FirstStepBrochureWidgetsImports.dart';
import 'package:base_flutter/company/screens/company_opinion_subscribe/widgets/CompOpinionSubscribeWidgetsImports.dart';
import 'package:base_flutter/general/blocks/generic_cubit/generic_cubit.dart';
import 'package:base_flutter/general/constants/MyColors.dart';
import 'package:base_flutter/general/widgets/DefaultAppBar.dart';
import 'package:base_flutter/general/widgets/DefaultButton.dart';
import 'package:flutter/material.dart';
part 'FirstStepBrochure.dart';
part 'FirstStepBrochureData.dart';