import 'package:base_flutter/general/constants/CustomButtonAnimation.dart';
import 'package:base_flutter/general/resources/GeneralRepository.dart';
import 'package:base_flutter/general/screens/forget_password_code/widgets/ForgetPassCodeWidgetsImports.dart';
import 'package:base_flutter/general/widgets/AuthScaffold.dart';
import 'package:base_flutter/general/widgets/HeaderLogo.dart';
import 'package:base_flutter/general/widgets/LoadingButton.dart';
import 'package:flutter/material.dart';
part 'ForgetPasswordCode.dart';
part 'ForgetPasswordCodeData.dart';